// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function GetActiveProfile() {
  return window['go']['main']['App']['GetActiveProfile']();
}

export function GetPaths() {
  return window['go']['main']['App']['GetPaths']();
}

export function ListProfiles() {
  return window['go']['main']['App']['ListProfiles']();
}

export function SetSaveGamePath(arg1) {
  return window['go']['main']['App']['SetSaveGamePath'](arg1);
}

export function SwitchProfile(arg1) {
  return window['go']['main']['App']['SwitchProfile'](arg1);
}
