// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function DeleteProfile(arg1) {
  return window['go']['main']['App']['DeleteProfile'](arg1);
}

export function EnsureProfilesFolder() {
  return window['go']['main']['App']['EnsureProfilesFolder']();
}

export function ExportProfileBundle(arg1, arg2) {
  return window['go']['main']['App']['ExportProfileBundle'](arg1, arg2);
}

export function GetActiveProfile() {
  return window['go']['main']['App']['GetActiveProfile']();
}

export function GetPaths() {
  return window['go']['main']['App']['GetPaths']();
}

export function ImportProfileBundle(arg1, arg2) {
  return window['go']['main']['App']['ImportProfileBundle'](arg1, arg2);
}

export function ListProfiles() {
  return window['go']['main']['App']['ListProfiles']();
}

export function PickExportBundlePath() {
  return window['go']['main']['App']['PickExportBundlePath']();
}

export function PickImportBundlePath() {
  return window['go']['main']['App']['PickImportBundlePath']();
}

export function PrepareFreshProfile(arg1) {
  return window['go']['main']['App']['PrepareFreshProfile'](arg1);
}

export function RenameProfile(arg1, arg2) {
  return window['go']['main']['App']['RenameProfile'](arg1, arg2);
}

export function RunHealthCheck() {
  return window['go']['main']['App']['RunHealthCheck']();
}

export function SaveCurrentProfile(arg1) {
  return window['go']['main']['App']['SaveCurrentProfile'](arg1);
}

export function SetSaveGamePath(arg1) {
  return window['go']['main']['App']['SetSaveGamePath'](arg1);
}

export function CreateMarkerFile(arg1) {
  return window['go']['main']['App']['CreateMarkerFile'](arg1);
}

export function SwitchProfile(arg1) {
  return window['go']['main']['App']['SwitchProfile'](arg1);
}
